<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Sign up Sample">
        <meta name="author" content="">
        <meta name="robots" content="noindex">
        <meta name="googlebot" content="noindex">
        <!-- normal browser shortcut icon : for IE and Others -->
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="icon" type="image/x-icon" href="/favicon.ico">

        <title>Login</title>
        
        <!-- Fontawesome 5.6.3 -->
        <link href="/vendor/sb-admin-2/vendor/fontawesome/css/all.min.css" rel="stylesheet" type="text/css">
        <!-- SB Admin 2 CSS -->
        <link href="/vendor/sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet" type="text/css">
        <!-- Customize -->
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
        <link href="/css/register.css" rel="stylesheet" type="text/css">
    </head>
    <body class="bg-login-image">
        <div class="container">
            <!-- Outer Row -->
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-8 col-md-9">
                    <div class="card o-hidden border-0 shadow my-5" style="border-radius: 18px;">
                        <div class="card-body p-0">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                                <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->
                                <div class="col-lg-10 m-auto">
                                    <div class="p-5">
                                        <div class="text-center mb-5 mt-5">
                                            <h1 class="text-gray-600"><b>Login</b></h1>
                                        </div>
                                        <form id="login-form" class="user" action="<?= strtok( $_SERVER["REQUEST_URI"],'?' );?>" method="post">
                                            <div class="text-danger text-center" id="message"></div>
                                            <div class="form-group">
                                                <input id="email" name="email" type="email" class="form-control form-control-user" aria-describedby="emailHelp" placeholder="Email" required autofocus>
                                            </div>
                                            <div class="form-group">
                                                <input id="password" name="password" type="password" class="form-control form-control-user" placeholder="Password" required>
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox small">
                                                    <input id="remember" name="remember" type="checkbox" class="custom-control-input" value="1" checked>
                                                    <label class="custom-control-label text-gray-600" for="remember">Remember Me</label>
                                                </div>
                                            </div>
                                            <input type="hidden" name="token" value="<?= $template_var['token'] ?>">
                                            <button type="submit" class="text btn btn-primary btn-user btn-block">Login</button>
                                        </form>
                                        <hr>
                                        <div class="text-center">
                                            <a href="/password/forget">Forget Password?</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.col-lg-6 -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
        
        <!-- JavaScript -->
        <!-- jQuery 3.3.1 -->
        <script src="/vendor/sb-admin-2/vendor/jquery/jquery.min.js" charset="utf-8"></script>
        <!-- Bootstrap Core JavaScript 4.2.1 -->
        <script src="/vendor/sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js" charset="utf-8"></script>
        <!-- JQuery Plug-In JavaScript -->
        <script src="/vendor/sb-admin-2/vendor/jquery-easing/jquery.easing.min.js" charset="utf-8"></script>
        <!-- SB-Admin 2 JavaScript -->
        <script src="/vendor/sb-admin-2/js/sb-admin-2.min.js" charset="utf-8"></script>
        <!-- Fontawesome 5.6.3 -->
        <script src="/vendor/sb-admin-2/vendor/fontawesome/js/all.min.js" charset="utf-8"></script>
        <!-- Custom JavaScript -->
        <script src="/js/app.js?v=<?= time();?>" charset="utf-8"></script>
        <script src="/js/sha512.js?v=<?= time();?>" charset="utf-8"></script>
        <script src="/js/login.js?v=<?= time();?>" charset="utf-8"></script>
    </body>
</html>