<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="robots" content="noindex">
        <meta name="googlebot" content="noindex">
        <!-- normal browser shortcut icon : for IE and Others -->
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="icon" type="image/x-icon" href="/favicon.ico">
        
        <title>One-Time Password</title>
        
        <!-- Fontawesome 5.6.3 -->
        <link href="/vendor/sb-admin-2/vendor/fontawesome/css/all.min.css" rel="stylesheet" type="text/css">
        <!-- SB Admin 2 CSS -->
        <link href="/vendor/sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet" type="text/css">
        <!-- Customize -->
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
        <link href="/css/register.css" rel="stylesheet" type="text/css">
    </head>
    <body class="bg-dark bg-password-image">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-7 col-md-9">
                    <div class="card border-0 shadow my-5" style="background-color:#EBEBEB; border-radius: 18px;">
                        <div class="card-body p-xl-5 p-lg-5">
                            <div class="text-center">
                                <h4 class="card-title font-header text-dark mt-3"><b>One-Time Password</b></h4>
                                <h6 class="mt-4 pl-4 pr-4 p-0" style="color:#858585;">After 180 seconds it will be expired</h6>
                            </div>
                            <form id="otp-pw-form" class="user" action="<?= strtok($_SERVER["REQUEST_URI"],'?');?>" method="post">
                                <div class="font-size-sm text-danger text-center" id="message"></div>
                                <div class="form-group mt-4 pl-4 pr-4 p-0">
                                    <div class="input-group">
                                        <input type="password" id="otp-pw-input" name="otp-pw-input" class="form-control" placeholder="Enter 6-Char Code From Email" required autofocus>
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Verify</button>
                                        </span>
                                    </div>
                                </div>
                                <input type="hidden" name="token" value="<?= $template_var['xcode'] ?>">
                                <div class="form-group d-flex pl-4 pr-4 p-0 m-0 mt-4">
                                    <a class="font-size-sm p-0 m-0 btn btn-link text-secondary justify-content-center-start" href="/login">&#8592; Login</a>
                                    <button type="button" id="resend-xcode" name="resend-xcode" class="font-size-md p-0 m-0 btn btn-link justify-content-end ml-auto text-info">Re-send veritication code</button>
                                </div>
                            </form>
                            <!-- /.text-center -->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
        <!-- /.container -->
        <!-- JavaScript -->
        <!-- jQuery 3.3.1 -->
        <script src="/vendor/sb-admin-2/vendor/jquery/jquery.min.js" charset="utf-8"></script>
        <!-- Bootstrap Core JavaScript 4.2.1 -->
        <script src="/vendor/sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js" charset="utf-8"></script>
        <!-- JQuery Plug-In JavaScript -->
        <script src="/vendor/sb-admin-2/vendor/jquery-easing/jquery.easing.min.js" charset="utf-8"></script>
        <!-- SB-Admin 2 JavaScript -->
        <script src="/vendor/sb-admin-2/js/sb-admin-2.min.js" charset="utf-8"></script>
        <!-- Fontawesome 5.6.3 -->
        <script src="/vendor/sb-admin-2/vendor/fontawesome/js/all.min.js" charset="utf-8"></script>
        <!-- Customized js -->
        <script src="/js/app.js" charset="utf-8"></script>
        <script src="/js/otp-pw.js?v=<?= time();?>" charset="utf-8"></script>
    </body>
</html>