<!DOCTYPE html>
<html lang="en">
<head>
    <title>One-Time Password</title>
</head>
<body>
<p>
    You are going to sign-in account, and the OTP is "<?= $xcode;?>".
</p>
<p><b>If you don't request the OTP, but you get the one, it might be someone trying to sign in your account.
        Please change your password as soon as possible to defence hacker attack!</b></p>
<small>- This is a system email, please do not reply.</small>
</body>
</html>