<!DOCTYPE html>
<html lang="en">
<head>
    <title>Reset Password Notification</title>
</head>
<body>
    <p>Your account password has been reset! This mail has a unique reset link for you as below. 
    Please reset it in a day. If it is expired, reset it on forget-password page again.</p>
    <p><b>If it was not you, please contact to administrator ASAP.</b></p>
    <br/>
    <p><b>Reset new password link:</b> <a href="<?= $url;?>" target="_blank" rel="noreferrer nofollow external noopener"><?= $url;?></a></p>
    <br/>
    <small>- This is a system email, please do not reply.</small>
</body>
</html>