<!DOCTYPE html>
<html lang="en">
<head>
    <title>Congratulation! You get invitation from {your website name}</title>
</head>
<body>
    <p>
        This is for invitee. Open the confirming link and you can start {your website name} using.
    </p>
    <p>
        <b>Confirming Link:</b>
        <a href="<?= $url;?>" target="_blank" rel="noreferrer nofollow external noopener"><?= $url;?></a>
    </p>
    <small>- This is a system email, please do not reply.</small>
</body>
</html>